### ISSUE TITLE
VS Code/CMake cannot locate MKL libraries 

### ISSUE THREAD

**Issue by wbsteinMSFC** [AlabamaASRL/asset_asrl#5]
First issue!

When installing via VS code/CMake, it could not locate MKL libraries eventhough they have been installed (via previous instructions) and have been properly sourced. 

Is there a command/area of the cmake that can be hot-wired so that cmake can find it?

**Comment by jasonmeverett** [comment]
Have you tried updating your `LD_LIBRARY_PATH` environment variable to include the OneAPI lib directory before running CMake? Not sure how to do this through VSCode though

**Comment by wbsteinMSFC** [comment]
Hey man!

No. I added it to my zsh, no dice (various versions of the mkl path). I did figure out and then directly modify the CMakeCache.txt file. Added:

//Path to a library.
MKL_CORE_LIBRARY:FILEPATH=/opt/intel/oneapi/mkl/2023.0.0/lib/

//Path to a file.
MKL_INCLUDE_DIR:PATH=/opt/intel/oneapi/mkl/2023.0.0/include

//Path to a library.
MKL_INTERFACE_LIBRARY:FILEPATH=/opt/intel/oneapi/mkl/2023.0.0/interfaces

//Path to a library.
MKL_OMP_LIBRARY:FILEPATH=/opt/intel/oneapi/compiler/latest/mac/compiler/lib/libiomp5.dylib

//Path to a library.
MKL_SEQTHR_LIBRARY:FILEPATH=/opt/intel/oneapi/mkl/2023.0.0/lib/

Now it seems happy, er. Something else broke. but that's not unexpected since I'm on an M1.

**Comment by wbsteinMSFC** [comment]
> 

Thanks! That makes sense.

**Comment by jasonmeverett** [comment]
After working on Docker implementation w/ conda's [MKL](https://anaconda.org/anaconda/mkl) and [MKL Headers](https://anaconda.org/anaconda/mkl-include), another option is to set `MKLROOT` before running CMake. As per [FindMKL.cmake](https://github.com/AlabamaASRL/asset_asrl/blob/master/cmake/FindMKL.cmake#L21), this is the environment variable used to find MKL.

Into `.bashrc` or equivalent:
```
export MKLROOT=/path/to/MKL
```

**Comment by jasonmeverett** [comment]
Also, should this issue be closed?

**Comment by wbsteinMSFC** [comment]
I dunno. I just figured Mac/M1 would be very niche and a low priority. Until there is an easy path where clang/etc supports the architecture in the sameway that was intended by the developers, I’m not sure there is a way forward.

If you’d like to repopen it feel free. You guys are the boss :D

        William Stein
        Mission Analysis and Optimization Tech Fellow
        Jacobs Space Exploration Group | ESSCA Contract
        (256).961.1437 (o)
        ***@***.***



From: jasonmeverett ***@***.***>
Reply-To: AlabamaASRL/asset_asrl ***@***.***>
Date: Sunday, January 8, 2023 at 11:25 AM
To: AlabamaASRL/asset_asrl ***@***.***>
Cc: William Stein ***@***.***>, Author ***@***.***>
Subject: [EXTERNAL] Re: [AlabamaASRL/asset_asrl] VS Code/CMake cannot locate MKL libraries (Issue #5)


Also, should this issue be closed?

**Comment by jasonmeverett** [comment]
@jbpezent what kind of effort would it be to build an OpenBLAS implementation or equivalent to dodge MKL dependency?

**Comment by jbpezent** [comment]
@jasonmeverett , **Enormous**. We are using MKL PARDISO as the symmetric-indefinite linear solver inside the optimizer. From our testing it was significantly faster than the other freely available alternatives that could use an alternative BLAS backend(ex: MUMPS and MA-27). MA-57 and MA-86 are supposed to have similar performance but have weird licensing requirements for non-academic users. So we cant really replace MKL PARDISO without either incurring a significant performance loss or requiring users to acquire commercial/licensed software. 

A long term goal is to write our own replacement symmetric-indefinite linear solver that uses Eigen as its BLAS backend with the option to also use MKL or OpenBLAS. This would also liberate us from x86 processors, and allow asset to run on Arm and M1 Macs. However, significant R&D would be required to develop something that even comes close to being as fast as MKL PARDISO.
