### ISSUE TITLE
Compiling on a Mac/M1 architecture

### ISSUE THREAD

**Issue by wbsteinMSFC** [AlabamaASRL/asset_asrl#7]
I know this isn't a high priority, and I'm playing around with this as an academic curiosity (I mainly will be running asset on linux anyways).  

I've followed the linux install docs and so far so good (with a couple of intellectual jumps for those familiar with Macs etc). 

I end up with the following compiler error:
**[build] clang: error: the clang compiler does not support '-march=native'**

Since I'm not very familiar with compiling Asset, I figured I'd document this. Especially if it's an easy fix.

This isn't a priority so no need to rush to respond (unless you're bored :D)

**Comment by jbpezent** [comment]
@wbsteinMSFC You may be able to get it to compile on an M1 Mac, but I'd imagine it will throw an illegal instruction error as soon as you run the optimizer. The optimizer depends on intel MKL, which unfortunately doesn't support ARM cpus at the moment. As for the compiler error it seems that clang does not support -march=native on M1 macs.
[https://stackoverflow.com/questions/65966969/why-does-march-native-not-work-on-apple-m1](url)

**Comment by wbsteinMSFC** [comment]
@jbpezent Yeah. I kinda figured. Although I was going to try to bootstrap MKL through rosetta, not the fastest way. But production would be on linux and tinkering would be on Mac. It looks like (rumor) that clang15 supports -march-native on M1. But VS Code was content with the other compilers it had and decided to ignore my freshly installed clang15. So we are not friends at the moment. :D

I may revisit this when I have more time, but it's a nice to have. The linux version is compiling as I type. Thanks guys!

**Comment by wgledbetter** [comment]
Regarding vscode not using clang 15, did you re-run "scan for kits" after installing it?

**Comment by wbsteinMSFC** [comment]
Haha. Yeah. No dice.
I just got mad at it and started working on linux instead. No issues.

        William Stein
        Mission Analysis and Optimization Tech Fellow
        Jacobs Space Exploration Group | ESSCA Contract
        (256).961.1437 (o)
        ***@***.***



From: William Ledbetter ***@***.***>
Reply-To: AlabamaASRL/asset_asrl ***@***.***>
Date: Friday, January 6, 2023 at 8:22 AM
To: AlabamaASRL/asset_asrl ***@***.***>
Cc: William Stein ***@***.***>, State change ***@***.***>
Subject: [EXTERNAL] Re: [AlabamaASRL/asset_asrl] Compiling on a Mac/M1 architecture (Issue #7)


Regarding vscode not using clang 15, did you re-run "scan for kits" after installing it?
